package ua.training.project.constant;

public interface Path {
    String REDIRECT = "redirect:";
    String LOGIN_PAGE = "/login.jsp";
    String LOGIN = "/login";
    String LOGOUT = "/logout";
    String LOGIN_PRG = "/loginPrg";
    String HOMEPAGE = "/index.jsp";
    String ADMIN_PAGE = "/admin.jsp";
    String ADMIN = "/admin";
    String USER_PAGE = "/user.jsp";
    String USER = "/user";
    String ERROR_PAGE = "/error.jsp";
    String ERROR = "/error";
    String REGISTRATION_PAGE = "/registration.jsp";
    String REGISTRATION = "/registration";
    String REGISTRATION_PRG = "/registrationPrg";
    String PROFILE_PAGE = "/profile.jsp";
    String PROFILE = "/profile";
    String UPDATE_PAGE = "/update.jsp";
    String UPDATE = "/update";
    String ACTIVITY_REQUEST_PAGE = "/activities.jsp";
    String ACTIVITY_REQUEST = "/activities";
    String MANAGE_USERS = "/manageUsers";
    String DELETE_USERS = "/deleteUsers";
    String ADD_USERS = "/addUsers";
    String MANAGE_USERS_PAGE = "/manageUsers.jsp";
    String MANAGE_ACTIVITIES = "/manageActivities";
    String MANAGE_ACTIVITIES_PAGE = "/manageActivities.jsp";
    String DELETE_ACTIVITIES = "/deleteActivities";
    String ADD_ACTIVITIES = "/addActivities";
    String MANAGE_REQUESTS = "/manageRequests";
    String MANAGE_REQUESTS_PAGE = "/manageRequests.jsp";
    String USER_STAT_PAGE = "/userStat.jsp";
    String USER_STAT = "/userStat";
    String ACTIVITY_STAT_PAGE = "/activityStat.jsp";
    String ACTIVITY_STAT = "/activityStat";
}
